version: "3"
services:
  clickhouse-server:
    image: "yandex/clickhouse-server:latest"
    ports:
      - "18123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./clickhouse_database:/var/lib/clickhouse

  grafana-server:
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: vertamedia-clickhouse-datasource

    volumes:
      - ./grafana:/var/lib/grafana